name: Lint and Test

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' # pre-commit-ci/lite-action only runs here
    strategy:
      matrix:
        # TODO: add Python 3.13 after tensorflow support: https://github.com/tensorflow/tensorflow/issues/78774
        # and pyonmttok supports Python 3.12+: https://github.com/OpenNMT/Tokenizer/issues/329
        python-version: [3.11] # Our min supported Python version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For setuptools-scm, replace with fetch-tags after https://github.com/actions/checkout/issues/1471
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: echo "UV_PROJECT_ENVIRONMENT=$(python -c "import sysconfig; print(sysconfig.get_config_var('prefix'))")" >> $GITHUB_ENV
      - run: uv python pin ${{ matrix.python-version }} # uv requires .python-version to match OS Python: https://github.com/astral-sh/uv/issues/11389
      - run: uv sync --python-preference only-system
      - run: git checkout .python-version # For clean git diff given `pre-commit run --show-diff-on-failure`
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync
      - name: Login to Hugging Face Hub
        run: uv run huggingface-cli login --token $HUGGINGFACE_HUB_ACCESS_TOKEN
        env:
          HUGGINGFACE_HUB_ACCESS_TOKEN: ${{ secrets.HUGGINGFACE_HUB_ACCESS_TOKEN }}
      - run: uv run pytest -n auto src tests
      - name: Clear molbloom cache # Work around https://github.com/whitead/molbloom/issues/30
        run: rm -rf /home/runner/.cache/molbloom
      - run: uv run pytest -n auto packages/remotes
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: add Python 3.13 after tensorflow support: https://github.com/tensorflow/tensorflow/issues/78774
        # and pyonmttok supports Python 3.12+: https://github.com/OpenNMT/Tokenizer/issues/329
        python-version: [3.11] # Our min supported Python version
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv python pin ${{ matrix.python-version }}
      - run: uv sync --python-preference=only-managed
      - run: uv run refurb src tests packages/remotes
      - run: uv run pylint src tests packages/remotes
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1
